
Restfood\Entity\Dish:
    type: entity
    table: dishes
    repositoryClass: Restfood\Entity\DoctrineResourceRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        uuid:
            type: guid
            unique: true
        name:
            type: string
            unique: true
            length: 100
    manyToMany:
        ingredients:
            targetEntity: Ingredient
            joinTable:
                name: dishes_ingredients
                joinColumns:
                    dish_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    ingredient_id:
                        referencedColumnName: id
            inversedBy: dishes