Restfood\Entity\Ingredient:
    type: entity
    table: ingredients
    repositoryClass: Restfood\Entity\DoctrineResourceRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        uuid:
            type: guid
            unique: true
        name:
            type: string
            unique: true
            length: 100
    manyToMany:
        allergens:
            targetEntity: Allergen
            joinTable:
                name: ingredients_allergens
                joinColumns:
                    ingredient_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    allergen_id:
                        referencedColumnName: id
            inversedBy: ingredients
        dishes:
            targetEntity: Dish
            mappedBy: ingredients